### ISSUE TITLE
Addon Support

### ISSUE THREAD

**Issue by Elderwolf1700** [gunnaraas/watermeter#1]
I love that you figured this out to work with my same water meter. Before I go buying anything, I saw you wanted to make a plugin for HA and was wondering if [this](https://community.home-assistant.io/t/home-assistant-add-on-amr2mqtt/378196) plugin would work? It looks to do the same with reading rtl-sdr.

**Comment by nudeymagazineday** [comment]
thanks for posting your code! I used it for awhile with just my water meter. Eventually I figured out how to get my gas meter in too and I started using [this](https://github.com/allangood/rtlamr2mqtt) add-on

**Comment by Elderwolf1700** [comment]
I can't take credit for the code. I was just curious if a plugin was already available to do what is needed. Glad to see you found a solution and can't wait to get it working once my reader comes.

**Comment by Elderwolf1700** [comment]
Since you have the same water meter, what model gas meter do you have? Found my water meter and my neighbors too but my gas doesn't appear at all. Mine is an older AC-250 with a GasLX module, which seems it might have a proprietary signal.

**Comment by nudeymagazineday** [comment]
I have an AC-250 also, but it’s using an Itron 100G DLS, ERG-5006-001 module. Sent from my iPhoneOn Apr 22, 2024, at 3:29 AM, Elderwolf1700 ***@***.***> wrote:﻿
Since you have the same water meter, what model gas meter do you have? Found my water meter and my neighbors too but my gas doesn't appear at all. Mine is an older AC-250 with a GasLX module, which seems it might have a proprietary signal.

**Comment by dolfelt** [comment]
I am also using that Addon with both a water meter and my gas meter. I've set the frequency in the `rtlamr` options and it seems to pickup both.

custom_parameters
```yaml
rtlamr: "-unique=true -duration=3m -centerfreq=912000000"
```

meters
```yaml
- id: xxxxxx
  protocol: scm
  name: gas_meter
  format: "######"
  unit_of_measurement: ft³
  icon: mdi:meter-gas
  device_class: gas
- id: xxxxxx
  protocol: r900
  name: water_meter
  format: "#####.##"
  unit_of_measurement: yd³
  icon: mdi:cup-water
  device_class: water
```

To get the conversion to gallons, I disabled `ha_autodiscovery` and created a manual `mqtt` sensor in my `configuration.yaml`. You would have to add both of them if not already discovered.

configuration.yaml
```yaml
mqtt:
  sensor:
    - name: Water Meter
      icon: mdi:cup-water
      unique_id: "<water-meter-id>"
      state_topic: rtlamr/<water-meter-id>/state
      force_update: true
      value_template: "{{ ((value | float) * 201.974) | round }}"
      unit_of_measurement: "gal"
      device_class: water
      state_class: total_increasing
      json_attributes_topic: rtlamr/<water-meter-id>/attributes

    - name: Gas Meter
      icon: mdi:meter-gas
      unique_id: "<gas-meter-id>"
      state_topic: rtlamr/<gas-meter-id>/state
      force_update: true
      unit_of_measurement: "ft³"
      device_class: gas
      state_class: total_increasing
      json_attributes_topic: rtlamr/<gas-meter-id>/attributes
```
